# Financial Market Prediction Using AutoML

# Developed by DEEPAK.M AI Generalist iPEC Solutions Private Limited Bangalore.

# 1..Import Libraries

In [1]:
import pandas as pd
from pycaret.classification import *

# 2.Load Dataset

In [2]:
import pandas as pd
df=pd.read_csv('pricol.csv')
df.head()

,Unnamed: 0,open,high,low,close,adjclose,volume,ticker
0,2002-07-01,6.880715,7.529671,6.880715,7.458553,3.088558,5732.0,PRICOLLTD.NS
1,2002-07-02,7.707468,8.045281,7.414104,7.965272,3.298388,6090.0,PRICOLLTD.NS
2,2002-07-03,8.365314,8.400873,7.938603,8.107509,3.357289,4783.0,PRICOLLTD.NS
3,2002-07-04,8.240857,8.800915,8.063060,8.685347,3.596569,6357.0,PRICOLLTD.NS
4,2002-07-05,8.596449,9.112058,8.471992,9.049830,3.747500,8553.0,PRICOLLTD.NS

In [3]:
df = df.drop(['Unnamed: 0'], axis=1)

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5430 entries, 0 to 5429
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   open      5422 non-null   float64
 1   high      5422 non-null   float64
 2   low       5422 non-null   float64
 3   close     5422 non-null   float64
 4   adjclose  5422 non-null   float64
 5   volume    5422 non-null   float64
 6   ticker    5430 non-null   object
dtypes: float64(6), object(1)
memory usage: 297.1+ KB
None

# 3.Checking Missing Values

In [5]:
print(df.isnull().sum())

open        8
high        8
low         8
close       8
adjclose    8
volume      8
ticker      0
dtype: int64

# 4.Create target column

In [6]:
df['Target'] = (df['close'].shift(-1) > df['close']).astype(int)

In [7]:
df = df.drop(['ticker'], axis=1)

# 5.Fill the missing values

In [8]:
df = df.ffill()

In [9]:
print(df.isnull().sum())

open        0
high        0
low         0
close       0
adjclose    0
volume      0
Target      0
dtype: int64

In [10]:
df.head()

       open      high       low     close  adjclose  volume  Target
0  6.880715  7.529671  6.880715  7.458553  3.088558  5732.0       1
1  7.707468  8.045281  7.414104  7.965272  3.298388  6090.0       1
2  8.365314  8.400873  7.938603  8.107509  3.357289  4783.0       1
3  8.240857  8.800915  8.063060  8.685347  3.596569  6357.0       1
4  8.596449  9.112058  8.471992  9.049830  3.747500  8553.0       1

# 6.Set up Pycaret

In [11]:
s = setup(
    data=df,
    target='Target',
    session_id=123,
    normalize=True
)

# 7.Compare Algorithms

In [12]:
best_model = compare_models()

Processing:   0%|          | 0/69 [00:00<?, ?it/s]

# 8.Train Best Model

In [13]:
final_model = finalize_model(best_model)

# 9.Check Accuracy

In [15]:
evaluate_model(final_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

# 10.Predict

In [16]:
predictions = predict_model(final_model)
print(predictions.head())

            open        high         low       close    adjclose    volume  \
5021  171.399994  174.500000  171.000000  172.199997  172.199997  391691.0
1623    6.045073    6.045073    6.045073    6.045073    5.088097       0.0
2661   16.268358   16.401705   15.868316   16.090563   14.663239   63947.0
1245   28.447401   28.536301   28.091810   28.358503   22.345867   53204.0
4274   23.958048   26.447193   23.424658   25.513763   25.513763  187286.0

      Target  prediction_label  prediction_score
5021       0                 1            0.5981
1623       1                 0            0.6501
2661       0                 0            0.6539
1245       1                 0            0.6466
4274       0                 0            0.6129

# 11.Save mode